Repository youcan-shop/cli, pull requests merged in 2024-12, with the labels that each got.

#78 feat(cli-kit): use pkce for authentication
  packages/cli-kit/lib/node/crypto.ts
  packages/cli-kit/lib/node/env.ts
  packages/cli-kit/lib/node/session.ts
Labels: ✅ Reviewed

#76 APPS-4 : Add useful hotkeys to the dev command
  package.json
  packages/app/lib/cli/commands/app/dev.ts
  packages/app/lib/cli/services/dev/workers/app-worker.ts
  packages/app/lib/cli/services/dev/workers/index.ts
  packages/app/lib/cli/services/dev/workers/theme-extension-worker.ts
  packages/app/lib/cli/services/dev/workers/web-worker.ts
  packages/app/lib/types.ts
  packages/app/rollup.config.js
  packages/app/tsconfig.json
  packages/cli-kit/lib/index.ts
  packages/cli-kit/lib/node/cli.ts
  packages/cli-kit/lib/node/config.ts
  packages/cli-kit/lib/node/filesystem.ts
  packages/cli-kit/lib/node/system.ts
  packages/cli-kit/lib/node/worker.ts
  packages/cli-kit/lib/ui/components/DevOutput.tsx
  packages/cli-kit/lib/ui/components/HotKeys.tsx
  packages/cli-kit/lib/ui/components/utils/symbols.tsx
  packages/cli-kit/lib/ui/index.ts
  packages/cli-kit/package.json
  packages/cli-kit/rollup.config.js
  packages/cli-kit/tsconfig.json
  packages/cli/rollup.config.js
  packages/cli/tsconfig.json
  packages/create-app/lib/services/init.ts
  packages/create-app/rollup.config.js
  packages/create-app/tsconfig.json
  packages/theme/lib/cli/commands/theme/dev.ts
  packages/theme/lib/cli/services/dev/execute.ts
  packages/theme/lib/cli/services/dev/worker.ts
  packages/theme/lib/types.ts
  packages/theme/rollup.config.js
  packages/theme/tsconfig.json
  pnpm-lock.yaml
  tsconfig.json
Labels: 💻 Ready for review, ✅ Reviewed

#79 APPS-3 : Automatically configure the app's env when running dev
  packages/app/lib/cli/commands/app/dev.ts
  packages/app/lib/cli/services/dev/workers/app-worker.ts
  packages/app/lib/cli/services/dev/workers/index.ts
  packages/app/lib/cli/services/dev/workers/web-worker.ts
  packages/app/lib/types.ts
Labels: 💻 Ready for review

#81 DARK : update `APP_URL` environment variable value
  packages/app/lib/cli/commands/app/dev.ts
Labels: 💻 Ready for review

#80 APPS-11 : CLI > Add a command to show the env variables needed by the app to run
  packages/app/lib/cli/commands/app/dev.ts
  packages/app/lib/cli/commands/app/env/show.ts
  packages/app/lib/cli/commands/app/generate/extension.ts
  packages/app/lib/cli/commands/app/install.ts
  packages/app/lib/util/app-command.ts
  packages/app/lib/util/theme-command.ts
  packages/app/package.json
Labels: 💻 Ready for review

#82 APPS-3 : Automatically configure the app's env when running dev - 2
  packages/app/lib/cli/commands/app/dev.ts
  packages/app/lib/types.ts
  packages/app/lib/util/app-command.ts
Labels: 💻 Ready for review

#77 APPS-5 : Use a tunneling solution to host the app
  packages/app/lib/cli/commands/app/dev.ts
  packages/app/lib/cli/services/dev/workers/index.ts
  packages/app/lib/cli/services/dev/workers/tunnel-worker.ts
  packages/app/lib/util/app-command.ts
  packages/cli-kit/lib/index.ts
  packages/cli-kit/lib/node/filesystem.ts
  packages/cli-kit/lib/services/cloudflared.ts
  packages/cli-kit/lib/services/index.ts
  packages/cli-kit/package.json
  pnpm-lock.yaml
Labels: 💻 Ready for review

#83 APPS-13 : Rotate to the next port if the current chosen one is busy
  packages/app/lib/cli/commands/app/dev.ts
  packages/app/lib/cli/services/dev/workers/tunnel-worker.ts
  packages/cli-kit/lib/node/system.ts
  packages/cli-kit/lib/services/cloudflared.ts
Labels: 💻 Ready for review
